-- ============================================================================
-- Migration: Add Campaign Sequences System
-- ============================================================================
-- Description: Adds multi-step campaign automation tables (separate from existing campaign tracking)
-- Date: 2025-11-17
-- Source: Adapted from ai-outreach-lambda/migrations/001_add_workflow_system.sql
--
-- NOTE: This is SEPARATE from existing campaigns table which tracks events.
--       campaign_sequences = automation blueprint (what should happen)
--       campaigns = event tracking (what did happen)
-- ============================================================================

-- ============================================================================
-- 1. CAMPAIGN SEQUENCES (Multi-step Campaigns)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.campaign_sequences (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255) NOT NULL,
  description TEXT,

  -- Target selection (SQL generated by AI agent)
  target_sql TEXT NOT NULL,
  target_count INTEGER,
  target_preview JSONB,
  /* Stores preview results for UI display before campaign starts */

  -- Campaign steps configuration
  steps JSONB NOT NULL,
  /* Example:
  [
    {
      "step_number": 1,
      "template_id": "uuid",
      "delay_days": 0,
      "subject_template": "Introduction to {product_name}",
      "llm_instructions": "Personalize based on industry and role",
      "condition": null
    },
    {
      "step_number": 2,
      "template_id": "uuid",
      "delay_days": 3,
      "subject_template": "Follow-up: {product_name} Benefits",
      "condition": "opened_previous = true"
    },
    {
      "step_number": 3,
      "template_id": "uuid",
      "delay_days": 5,
      "subject_template": "Final call: Schedule a demo",
      "condition": "clicked_previous = true"
    }
  ]
  */

  -- Execution settings
  from_mailbox_id UUID REFERENCES public.mailboxes(id),
  send_time_preference VARCHAR(50),
  /* Example: "morning" (9-11am), "afternoon" (2-4pm), "optimal" (AI decides) */

  -- Link to backend product catalog
  product_id UUID REFERENCES public.products(id) ON DELETE SET NULL,

  -- Scheduling
  scheduled_at TIMESTAMPTZ,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,

  -- Status
  status VARCHAR(50) DEFAULT 'draft' CHECK (status IN (
    'draft',
    'scheduled',
    'running',
    'completed',
    'paused',
    'cancelled'
  )),

  -- Statistics (updated periodically)
  stats JSONB DEFAULT '{}',
  /* Example:
  {
    "total_enrolled": 150,
    "emails_sent": 120,
    "opened": 45,
    "clicked": 12,
    "replied": 3,
    "unsubscribed": 2
  }
  */

  -- Metadata
  created_by UUID REFERENCES public.profiles(profile_id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- 2. CAMPAIGN ENROLLMENTS (Track Contacts in Campaigns)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.campaign_enrollments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  campaign_sequence_id UUID NOT NULL REFERENCES public.campaign_sequences(id) ON DELETE CASCADE,
  contact_id UUID NOT NULL REFERENCES public.contacts(id) ON DELETE CASCADE,

  -- Progress tracking
  current_step INTEGER DEFAULT 1,
  next_send_date TIMESTAMPTZ,

  -- Status
  status VARCHAR(50) DEFAULT 'enrolled' CHECK (status IN (
    'enrolled',
    'active',
    'completed',
    'unsubscribed',
    'bounced',
    'paused'
  )),

  -- Step history
  steps_completed JSONB DEFAULT '[]',
  /* Example:
  [
    {
      "step": 1,
      "email_id": "uuid",
      "sent_at": "2024-11-14T09:00:00Z",
      "opened_at": "2024-11-14T09:15:00Z",
      "clicked_at": null
    }
  ]
  */

  -- Engagement tracking
  total_opens INTEGER DEFAULT 0,
  total_clicks INTEGER DEFAULT 0,
  replied BOOLEAN DEFAULT false,

  -- Timing
  enrolled_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ,

  -- Ensure contact only enrolled once per campaign
  UNIQUE(campaign_sequence_id, contact_id)
);

-- ============================================================================
-- INDEXES FOR PERFORMANCE
-- ============================================================================

-- Campaign Sequences
CREATE INDEX IF NOT EXISTS idx_campaign_sequences_status ON public.campaign_sequences(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_campaign_sequences_scheduled ON public.campaign_sequences(scheduled_at) WHERE status = 'scheduled';
CREATE INDEX IF NOT EXISTS idx_campaign_sequences_created_by ON public.campaign_sequences(created_by);
CREATE INDEX IF NOT EXISTS idx_campaign_sequences_product ON public.campaign_sequences(product_id) WHERE product_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_campaign_sequences_mailbox ON public.campaign_sequences(from_mailbox_id);

-- Campaign Enrollments
CREATE INDEX IF NOT EXISTS idx_campaign_enrollments_campaign ON public.campaign_enrollments(campaign_sequence_id, status);
CREATE INDEX IF NOT EXISTS idx_campaign_enrollments_contact ON public.campaign_enrollments(contact_id);
CREATE INDEX IF NOT EXISTS idx_campaign_enrollments_next_send ON public.campaign_enrollments(next_send_date) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_campaign_enrollments_status ON public.campaign_enrollments(status);

-- ============================================================================
-- TRIGGERS FOR UPDATED_AT
-- ============================================================================

CREATE TRIGGER update_campaign_sequences_updated_at
    BEFORE UPDATE ON public.campaign_sequences
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- ============================================================================
-- HELPER VIEWS
-- ============================================================================

-- View: Campaign Sequences with Enrollment Stats
CREATE OR REPLACE VIEW public.v_campaign_sequences_with_stats AS
SELECT
    cs.id,
    cs.name,
    cs.description,
    cs.status,
    cs.product_id,
    p.product_name,
    cs.from_mailbox_id,
    m.email as from_mailbox_email,
    cs.target_count,
    cs.scheduled_at,
    cs.started_at,
    cs.completed_at,
    cs.stats,
    COUNT(ce.id) as total_enrollments,
    COUNT(ce.id) FILTER (WHERE ce.status = 'active') as active_enrollments,
    COUNT(ce.id) FILTER (WHERE ce.status = 'completed') as completed_enrollments,
    COUNT(ce.id) FILTER (WHERE ce.replied = true) as replied_count,
    AVG(ce.total_opens) as avg_opens_per_contact,
    AVG(ce.total_clicks) as avg_clicks_per_contact,
    cs.created_at,
    cs.updated_at
FROM public.campaign_sequences cs
LEFT JOIN public.campaign_enrollments ce ON cs.id = ce.campaign_sequence_id
LEFT JOIN public.products p ON cs.product_id = p.id
LEFT JOIN public.mailboxes m ON cs.from_mailbox_id = m.id
GROUP BY cs.id, p.product_name, m.email;

-- View: Enrollments Due for Sending
CREATE OR REPLACE VIEW public.v_campaign_enrollments_due AS
SELECT
    ce.id as enrollment_id,
    ce.campaign_sequence_id,
    cs.name as campaign_name,
    cs.steps,
    ce.contact_id,
    c.email as contact_email,
    c.first_name,
    c.last_name,
    ce.current_step,
    ce.next_send_date,
    ce.steps_completed,
    cs.from_mailbox_id,
    m.email as from_mailbox_email
FROM public.campaign_enrollments ce
JOIN public.campaign_sequences cs ON ce.campaign_sequence_id = cs.id
JOIN public.contacts c ON ce.contact_id = c.id
LEFT JOIN public.mailboxes m ON cs.from_mailbox_id = m.id
WHERE ce.status = 'active'
  AND ce.next_send_date <= NOW()
  AND cs.status = 'running'
ORDER BY ce.next_send_date ASC;

-- ============================================================================
-- HELPER FUNCTIONS
-- ============================================================================

-- Function to get enrollments due for sending
CREATE OR REPLACE FUNCTION public.get_campaign_enrollments_due()
RETURNS TABLE(
    enrollment_id UUID,
    campaign_sequence_id UUID,
    campaign_name VARCHAR,
    contact_id UUID,
    contact_email VARCHAR,
    current_step INTEGER,
    next_send_date TIMESTAMPTZ
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        ce.id,
        ce.campaign_sequence_id,
        cs.name,
        ce.contact_id,
        c.email,
        ce.current_step,
        ce.next_send_date
    FROM public.campaign_enrollments ce
    JOIN public.campaign_sequences cs ON ce.campaign_sequence_id = cs.id
    JOIN public.contacts c ON ce.contact_id = c.id
    WHERE ce.status = 'active'
      AND ce.next_send_date <= NOW()
      AND cs.status = 'running';
END;
$$ LANGUAGE plpgsql STABLE;

COMMENT ON FUNCTION public.get_campaign_enrollments_due IS 'Get all active campaign enrollments ready to send';

-- ============================================================================
-- COMMENTS
-- ============================================================================

COMMENT ON TABLE public.campaign_sequences IS 'Multi-step email campaign sequences (automation blueprint)';
COMMENT ON TABLE public.campaign_enrollments IS 'Track contacts enrolled in campaign sequences';

COMMENT ON COLUMN public.campaign_sequences.target_sql IS 'AI-generated SQL query for selecting target contacts';
COMMENT ON COLUMN public.campaign_sequences.steps IS 'Array of campaign steps with templates, delays, and conditions';
COMMENT ON COLUMN public.campaign_sequences.stats IS 'Aggregated campaign statistics (sent, opened, clicked, replied)';

COMMENT ON COLUMN public.campaign_enrollments.steps_completed IS 'History of completed steps with engagement data';
COMMENT ON COLUMN public.campaign_enrollments.next_send_date IS 'When next email should be sent to this contact';

-- ============================================================================
-- GRANTS
-- ============================================================================

GRANT ALL ON public.campaign_sequences TO authenticated;
GRANT ALL ON public.campaign_sequences TO service_role;

GRANT ALL ON public.campaign_enrollments TO authenticated;
GRANT ALL ON public.campaign_enrollments TO service_role;

-- Migration complete!
